<?php

namespace DoctrineORMModule\Proxy\__CG__\Plano\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Plano extends \Plano\Entity\Plano implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Plano\\Entity\\Plano' . "\0" . 'idPlano', '' . "\0" . 'Plano\\Entity\\Plano' . "\0" . 'descPlano', '' . "\0" . 'Plano\\Entity\\Plano' . "\0" . 'qtdDias', '' . "\0" . 'Plano\\Entity\\Plano' . "\0" . 'valor');
        }

        return array('__isInitialized__', '' . "\0" . 'Plano\\Entity\\Plano' . "\0" . 'idPlano', '' . "\0" . 'Plano\\Entity\\Plano' . "\0" . 'descPlano', '' . "\0" . 'Plano\\Entity\\Plano' . "\0" . 'qtdDias', '' . "\0" . 'Plano\\Entity\\Plano' . "\0" . 'valor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Plano $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdPlano($idPlano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPlano', array($idPlano));

        return parent::setIdPlano($idPlano);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPlano()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPlano();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPlano', array());

        return parent::getIdPlano();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescPlano($descPlano)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescPlano', array($descPlano));

        return parent::setDescPlano($descPlano);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescPlano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescPlano', array());

        return parent::getDescPlano();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtdDias($qtdDias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtdDias', array($qtdDias));

        return parent::setQtdDias($qtdDias);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtdDias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtdDias', array());

        return parent::getQtdDias();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', array($valor));

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', array());

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
