<h3>Editar Exercicio</h3>
<br />
<?php

$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
    echo $this->formElement($form->get('idExercicio'));
    echo $this->formHidden($form->get('security'));

    echo $this->formLabel($form->get('nome'));
    echo $this->formElement($form->get('nome'));
    echo $this->formElementErrors($form->get('nome'), array('class' => 'form-element-error'));

    echo $this->formLabel($form->get('imagem'));
    echo $this->formElement($form->get('imagem'));
    echo $this->formElementErrors($form->get('imagem'), array('class' => 'form-element-error'));


    echo $this->formLabel($form->get('descricao'));
    echo $this->formElement($form->get('descricao'));
    echo $this->formElementErrors($form->get('descricao'), array('class' => 'form-element-error'));

    echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();
?>