<?php 

if($container->hasPages()):
    $accepts = 0;
    
    foreach ($container->getPages() as $page) {
        if ($this->navigation()->accept($page)) {
            $accepts ++;
        }
    }
    if ($accepts > 0) : ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                      <!-- img src="<?php //echo $this->basePath('img/logo/logo.jpg') ?>" width="30" alt="Administrativo"/-->&nbsp;Administrativo</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php                
                        foreach ($container->getPages() as $page) :
                            if (!$this->navigation()->accept($page)) continue;
                            if (!$page->isVisible(true)) continue; ?>
                                <li class="<?php echo $page->isActive(true)  ? 'active' : ''; ?>">
                                    <a href="<?php echo $page->getHref(); ?>"  <?php echo $page->getTarget() != "" ? sprintf('target="%s"', $page->getTarget()) : ''; ?> <?php if($page->hasPages()): ?> data-toggle="dropdown"<?php endif; ?> class=" <?php echo $page->hasPages() ? 'dropdown-toggle' : ''; ?>"><?php echo $page->getLabel(); ?></a>
                                    <?php if ($page->hasPages()) : ?>
                                        <ul class="dropdown-menu">
                                            <?php foreach ($page->getPages() as $childPage) : ?>
                                                <li class="<?php echo $childPage->isActive(true)  ? 'active' : ''; ?>"><a href="<?php echo $childPage->getHref(); ?>"><?php echo $childPage->getLabel(); ?></a></li>
                                            <?php endforeach; ?>     
                                        </ul>
                                    <?php endif; ?>
                                </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>
    <?php endif; ?>            
<?php endif; ?>